# -*- coding: utf-8 -*-
"""CP020001_BasicPython_Basic-Python-Part-I_toStudent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrVxKyMAlpBu5UHes0OT1JRNENHe_Wy5

# CP020001 Computer Programming (Basic Python I)

# What Are Data Types?
"""

x = 42
print(type(x))  # Output: <class 'int'>

y = 3.14
print(type(y))  # Output: <class 'float'>

z = 3 + 5j
print(type(z))  # Output: <class 'complex'>

name = "Python"
print(type(name))  # Output: <class 'str'>

greeting = "Hello"
name = "World"
print(greeting + " " + name)  # Concatenation: Output: "Hello World"
print(len(greeting))          # Length: Output: 5
print(greeting[0])            # Indexing: Output: "H"
print(greeting[-1])           # Negative Indexing: Output: "o"
print(greeting.upper())       # Uppercase: Output: "HELLO"

is_python_fun = True
print(type(is_python_fun))  # Output: <class 'bool'>
print(5 > 3)                # Output: True
print(3 > 5)                # Output: False